apiVersion: v1
kind: ConfigMap
metadata:
  name: diabetes-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: artifact/baseline_logreg.joblib
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000
  MODEL_NAME: diabetes
  MODEL_ALIAS: production